using System.Linq;
using Brigade.Net.Partie.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Brigade.Net.Partie.Engines.AspNetCore;

[Generator(LanguageNames.CSharp)]
public sealed class AspNetCorePartieGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("PartieHttpAttributes.g.cs", HttpRouteAttributes.Emit())
        );
        BrigadeGeneratorCore.Initialize(
            context, EmitRoute, EmitAdapter, HttpRouteAttributes.Discover,
            HttpRouteAttributes.DiscoverPolicies, HttpRouteAttributes.DiscoverPolicyFunctions
        );
    }

    private static string EmitRoute(RouteEmission route)
    {
        var parameters = route.Inputs.Select(input => Binding(input) + input.TypeName + " " + input.MemberName);
        var arguments = string.Join(", ", route.Inputs.Select(input => input.MemberName));
        var baseRoute = "global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName("
            + "global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(app, "
            + Literal(route.Pattern.Length == 0 ? "/" : route.Pattern) + ", new[] { " + Literal(route.Operation.ToUpperInvariant()) + " }, "
            + "static (" + string.Join(", ", parameters) + ") => " + route.DescriptorExpression
            + ".ExecuteAsync(new " + route.InputTypeName + "(" + arguments + "))), " + Literal(route.Name) + ")";

        if (route.PolicyFunctions.Length == 0 && route.Policies.Length == 0)
        {
            return baseRoute + ";\n";
        }

        var code = "{\nvar __routeBuilder = " + baseRoute + ";\n";
        foreach (var policyFunc in route.PolicyFunctions)
        {
            code += policyFunc + "(__routeBuilder);\n";
        }

        foreach (var policy in route.Policies)
        {
            var typeArguments = route.InputTypeName;
            if (policy.MethodName == "Command")
            {
                typeArguments += ", " + (route.Inputs.FirstOrDefault(input => input.Source == "Body")?.TypeName
                    ?? "global::Brigade.Net.Core.Results.Unit");
            }

            code += policy.PolicyTypeName + "." + policy.MethodName + "<" + typeArguments + ">(__routeBuilder);\n";
        }

        return code + "}\n";
    }

    private static string Binding(RouteInputEmission input)
    {
        if (input.Source == "Cancellation" || (input.Source == "Service" && IsFrameworkValue(input.TypeName)))
        {
            return "";
        }

        var attribute = input.Source == "Service" ? "FromServices" : "From" + input.Source;
        var arguments = input.Source is "Route" or "Query" ? "(Name = " + Literal(input.BindingName) + ")" : "";
        return "[global::Microsoft.AspNetCore.Mvc." + attribute + arguments + "] ";
    }

    private static bool IsFrameworkValue(string typeName) => typeName.TrimEnd('?') is
        "global::Microsoft.AspNetCore.Http.HttpContext" or "global::Microsoft.AspNetCore.Http.HttpRequest"
        or "global::Microsoft.AspNetCore.Http.HttpResponse" or "global::System.Security.Claims.ClaimsPrincipal"
        or "global::System.Threading.CancellationToken";

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private static string EmitAdapter(string registrations) => """
        // <auto-generated />
        #nullable enable
        namespace Microsoft.AspNetCore.Builder;
        internal static class PartieRoutingExtensions
        {
            public static global::Microsoft.AspNetCore.Builder.WebApplication UsePartieRoutes(
                this global::Microsoft.AspNetCore.Builder.WebApplication app
            )
            {
        """ + registrations + "\nreturn app;\n}\n}";
}