<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Generator\Brigade.Net.Partie.Generator.csproj" />
    <Compile Remove="Tests/**" />
  </ItemGroup>
  <Target Name="IncludeGeneratorCore" AfterTargets="GetTargetPathWithTargetPlatformMoniker">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(TargetDir)Brigade.Net.Partie.Generator.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
</Project>