using System.Linq;
using System.Text;
using Brigade.Net.Partie.Generator;
using Microsoft.CodeAnalysis;

namespace Brigade.Net.Partie.Engines.AspNetCore;

internal static class HttpRouteAttributes
{
    private const string AttributeNamespace = "Brigade.Net.Partie.Engines.AspNetCore";
    private static readonly string[] Verbs = { "Get", "Post", "Put", "Patch", "Delete", "Head", "Options" };

    public static RouteDeclaration? Discover(AttributeData attribute)
    {
        if (attribute.AttributeClass?.ContainingNamespace.ToDisplayString() != AttributeNamespace)
        {
            return null;
        }

        var verb = Verbs.FirstOrDefault(verb => attribute.AttributeClass.Name == verb + "Attribute");
        return verb is null ? null : new RouteDeclaration(
            attribute.ConstructorArguments.FirstOrDefault().Value as string ?? "",
            verb.ToUpperInvariant()
        );
    }

    public static string Emit()
    {
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\nnamespace " + AttributeNamespace + ";\n");
        foreach (var verb in Verbs)
        {
            source.Append("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]\n")
                .Append("internal sealed class ").Append(verb).Append("Attribute(string pattern = \"\") : global::System.Attribute\n{\n")
                .Append("public string Pattern { get; } = pattern;\n}\n");
        }

        return source.ToString();
    }
}