// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.DeleteV1;
public sealed class OrderDeleteV1CmdDto
{
    [global::Microsoft.AspNetCore.Mvc.FromRoute(Name = "orderId")]
    public required global::System.Guid @Id { get; set; }
}
