// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.DeleteV1;
[global::Brigade.Net.Expo.ExpoAttribute()]
public sealed class OrderDeleteV1CmdDto
{
    [global::Brigade.Net.Expo.CustomValidationAttribute(null)]
    [global::Microsoft.AspNetCore.Mvc.FromRoute(Name = "orderId")]
    public required global::System.Guid @Id { get; set; }
}
