// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Accounts.UpdateMariaDbV1;
public sealed class AccountUpdateMariaDbV1CmdDto
{
    [global::Microsoft.AspNetCore.Mvc.FromQuery]
    public int @Id { get; set; } = default!;

    [global::Microsoft.AspNetCore.Mvc.FromQuery]
    public string? @Note { get; set; } = default!;
}
