// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Mise.SQLite;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Partie.Extensions.Mise.SQLite.SqliteDbConfigProvider<, >), true)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class @SqliteDbConfigProviderAttribute([global::Brigade.Net.Partie.Parameter] string @ConnectionStringName) : global::System.Attribute
{
    public string @ConnectionStringName { get; } = @ConnectionStringName;
}
