<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Mise.Generator/Brigade.Net.Mise.Generator.csproj" PrivateAssets="all" />
    <None Include="$(TargetPath)" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(TargetDir)Brigade.Net.Mise.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
  <Target Name="IncludeGeneratorCore" AfterTargets="GetTargetPathWithTargetPlatformMoniker">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(TargetDir)Brigade.Net.Mise.Generator.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>
</Project>
