<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.15.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="Testcontainers.MySql" Version="4.15.0" />
    <PackageReference Include="Testcontainers.MariaDb" Version="4.15.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <ProjectReference Include="../../Source/Mise/Brigade.Net.Mise.csproj" />
    <ProjectReference Include="../../Source/Mise.SqlServer/Brigade.Net.Mise.SqlServer.csproj" />
    <ProjectReference Include="../../Source/Mise.PostgreSQL/Brigade.Net.Mise.PostgreSQL.csproj" />
    <ProjectReference Include="../../Source/Mise.SQLite/Brigade.Net.Mise.SQLite.csproj" />
    <ProjectReference Include="../../Source/Mise.MySQL/Brigade.Net.Mise.MySQL.csproj" />
    <ProjectReference Include="../../Source/Mise.MariaDb/Brigade.Net.Mise.MariaDb.csproj" />
  </ItemGroup>
</Project>
