// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Example.Domain.Orders.OrderProvider<, >), true)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class @OrderProviderAttribute() : global::System.Attribute
{
}
