// TODO: CHECK
﻿// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.SearchPostgreSqlV1;
internal static class @OrderSearchPostgreSqlV1HandlerRoute
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class GetAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.SearchPostgreSqlV1.OrderSearchPostgreSqlV1Handler>(path, "GET")
    {
    }
}
