// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.PolicyTesting;
internal static class @TestPolicyHandlerRoute
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class GetAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler>(path, "GET")
    {
    }
}
