using System.Linq;
using Brigade.Net.Partie.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Brigade.Net.Partie.Engines.AspNetCore;

[Generator(LanguageNames.CSharp)]
public sealed class AspNetCorePartieGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        BrigadeGeneratorCore.Initialize(
            context,
            EmitRoute,
            EmitAdapter,
            HttpRouteAttributes.Discover,
            HttpRouteAttributes.DiscoverPolicies,
            HttpRouteAttributes.DiscoverPolicyFunctions,
            EmitTypes,
            EmitGroup,
            HandlerRouteDeclarations.Create(context)
        );
    }

    private static string EmitRoute(RouteEmission route)
    {
        var parameters = route.Inputs.Select(
            input => input.Source == "Request"
                ? "[global::Microsoft.AspNetCore.Http.AsParameters] " + DtoType(route) + " " + input.MemberName
                : Binding(input) + input.TypeName + " " + input.MemberName
        );
        var arguments = string.Join(
            ", ",
            route.Inputs.Select(
                input => input.Source == "Request"
                    ? "new " + route.Request!.TypeName + " { " + string.Join(
                    ", ",
                    route.Request.Properties.Select(
                        property => "@" + property.Name + " = " + input.MemberName + ".@" + property.Name
                    )
                ) + " }" : input.MemberName
            )
        );
        var baseRoute = "global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName("
            + "global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods("
            + route.Groups.Last().Key + ", "
            + Literal(HttpPath(route.LocalPath)) + ", new[] { "
            + Literal(route.Operation.ToUpperInvariant()) + " }, "
            + "static (" + string.Join(", ", parameters) + ") => "
            + route.DescriptorExpression + ".ExecuteAsync(new "
            + route.InputTypeName + "(" + arguments + "))), "
            + Literal(route.Name) + ")";
        if (route.PolicyFunctions.Length == 0 && route.Policies.Length == 0)
        {
            return baseRoute + ";\n";
        }

        var code = "{\nvar __routeBuilder = " + baseRoute + ";\n";
        foreach (var policy in route.Policies)
        {
            var typeArguments = "";
            if (policy.GenericMethod)
            {
                typeArguments = "<" + DtoType(route);
                if (policy.MethodName == "Command")
                {
                    typeArguments += ", " + (route.Request!.Properties.FirstOrDefault(property =>
                        property.Source is "Body" or "Form")?.TypeName
                        ?? "global::Brigade.Net.Core.Results.Unit");
                }

                typeArguments += ">";
            }

            code += policy.PolicyTypeName
                + "." + policy.MethodName + typeArguments
                + "(__routeBuilder);\n";
        }

        foreach (var policyFunc in route.PolicyFunctions)
        {
            code += policyFunc + "(__routeBuilder);\n";
        }

        return code + "}\n";
    }

    private static string HttpPath(System.Collections.Generic.IEnumerable<string> path)
    {
        var joined = string.Join(
            "/",
            path.Select(part => part.Trim('/')).Where(part => part.Length != 0)
        );
        return joined.Length == 0 ? "" : "/" + joined;
    }

    private static string EmitGroup(RouteGroupEmission group) => "var " + group.Key
        + " = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup("
        + (group.ParentKey ?? "app")
        + ", " + Literal(HttpPath(group.Path)) + ");\n";

    private static string DtoType(RouteEmission route) => route.Request!.DtoTypeName;
    private static GeneratedDeclaration EmitTypes(RouteEmission route)
    {
        var ns = DtoType(route).Substring("global::".Length);
        var separator = ns.LastIndexOf('.');
        var name = ns.Substring(separator + 1);
        var source = "// <auto-generated />\n#nullable enable\n"
            + (separator < 0 ? "" : "namespace " + ns.Substring(0, separator) + ";\n")
            + route.Request!.Metadata + "public sealed class " + name + " {\n";
        foreach (var property in route.Request.Properties)
        {
            var attribute = "global::Microsoft.AspNetCore.Mvc.From" + property.Source;
            var arguments = property.BindingName is null ? "" : "(Name = " + Literal(property.BindingName) + ")";
            source += property.Metadata + "[" + attribute + arguments + "]\npublic " + (property.Required ? "required " : "") + property.TypeName + " @" + property.Name + " { get; set; }" + (property.Required ? "" : " = default!;") + "\n";
        }

        return new GeneratedDeclaration(route.Request.DtoHintName, source + "}\n");
    }

    private static string Binding(RouteInputEmission input)
    {
        if (input.Source == "Cancellation" || IsFrameworkValue(input.TypeName))
        {
            return "";
        }

        return "[global::Microsoft.AspNetCore.Mvc.FromServices] ";
    }

    private static bool IsFrameworkValue(string typeName)
    {
        return typeName.TrimEnd('?') is "global::Microsoft.AspNetCore.Http.HttpContext"
            or "global::Microsoft.AspNetCore.Http.HttpRequest"
            or "global::Microsoft.AspNetCore.Http.HttpResponse"
            or "global::System.Security.Claims.ClaimsPrincipal"
            or "global::System.Threading.CancellationToken";
    }
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
    private static string EmitAdapter(string registrations) => """
        // <auto-generated />
        #nullable enable
        namespace Microsoft.AspNetCore.Builder;
        internal static class PartieRoutingExtensions
        {
            public static global::Microsoft.AspNetCore.Builder.WebApplication UsePartieRoutes(
                this global::Microsoft.AspNetCore.Builder.WebApplication app
            )
            {
        """ + registrations + "\nreturn app;\n}\n}";
}
