// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.SearchMariaDbV1;
internal static class @OrderSearchMariaDbV1HandlerRoute
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class GetAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.SearchMariaDbV1.OrderSearchMariaDbV1Handler>(path, "GET")
    {
    }
}
