// <auto-generated />
#nullable enable
namespace Microsoft.AspNetCore.OpenApi;
internal static class ExpoOpenApiGeneratedExtensions
{
    public static global::Microsoft.AspNetCore.OpenApi.OpenApiOptions AddExpo(
        this global::Microsoft.AspNetCore.OpenApi.OpenApiOptions options
    )
    {
        options.AddSchemaTransformer(TransformSchemaAsync);
        options.AddOperationTransformer(TransformOperationAsync);
        return options;
    }

    private static global::System.Threading.Tasks.Task TransformSchemaAsync(
        global::Microsoft.OpenApi.OpenApiSchema schema,
        global::Microsoft.AspNetCore.OpenApi.OpenApiSchemaTransformerContext context,
        global::System.Threading.CancellationToken cancellationToken
    )
    {
        _ = cancellationToken;if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "Id":
AddInexact(propertySchema, "CustomValidationAttribute");
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "Customer":
ApplyMinimum(propertySchema, 2);
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Cmd))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "Body":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
case "ValidationCode":
ApplyMinimum(propertySchema, 1);
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidationPayload))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "RequiredText":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
case "GreaterConstant":
propertySchema.ExclusiveMinimum = "10";
break;
case "GreaterOrEqualConstant":
propertySchema.Minimum = "10";
break;
case "LessConstant":
propertySchema.ExclusiveMaximum = "10";
break;
case "LessOrEqualConstant":
propertySchema.Maximum = "10";
break;
case "EqualConstant":
propertySchema.Const = "10";
break;
case "NotEqualConstant":
propertySchema.Not = new global::Microsoft.OpenApi.OpenApiSchema { Const = "10" };
break;
case "GreaterProperty":
AddInexact(propertySchema, "ExclusiveMinimum");
break;
case "GreaterOrEqualProperty":
AddInexact(propertySchema, "Minimum");
break;
case "LessProperty":
AddInexact(propertySchema, "ExclusiveMaximum");
break;
case "LessOrEqualProperty":
AddInexact(propertySchema, "Maximum");
break;
case "EqualProperty":
AddInexact(propertySchema, "Equal");
break;
case "NotEqualProperty":
AddInexact(propertySchema, "NotEqual");
break;
case "EvenNumber":
AddInexact(propertySchema, "IsEvenAttribute");
break;
case "CustomCode":
AddInexact(propertySchema, "CustomValidationAttribute");
break;
case "ContactEmail":
propertySchema.Format = "email"; propertySchema.Pattern = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$";
break;
case "ReferenceCode":
propertySchema.Pattern = "^REF-\\d{4}$";
break;
case "DisplayName":
ApplyMinimum(propertySchema, 2);
ApplyMaximum(propertySchema, 40);
break;
case "Tags":
ApplyMinimum(propertySchema, 3); ApplyMaximum(propertySchema, 3);
break;
case "NonemptyText":
ApplyMinimum(propertySchema, 1);
break;
case "MeaningfulText":
AddInexact(propertySchema, "IsNotWhiteSpaceAttribute");
break;
case "State":
AddInexact(propertySchema, "IsDefinedEnumAttribute");
break;
case "Website":
propertySchema.Format = "uri";
break;
case "PhoneNumber":
propertySchema.Pattern = "^\\+[1-9]\\d{1,14}$";
break;
case "Uuid":
propertySchema.Format = "uuid";
break;
case "IpAddress":
propertySchema.Format = "ip";
break;
case "Ipv4Address":
propertySchema.Format = "ipv4";
break;
case "Ipv6Address":
propertySchema.Format = "ipv6";
break;
case "Base64":
propertySchema.Format = "byte";
break;
case "HexColor":
propertySchema.Pattern = "^#?(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$";
break;
case "Slug":
propertySchema.Pattern = "^[a-z0-9]+(?:-[a-z0-9]+)*$";
break;
case "Alpha":
propertySchema.Pattern = "^\\p{L}+$";
break;
case "AlphaNumeric":
propertySchema.Pattern = "^[\\p{L}\\p{Nd}]+$";
break;
case "Digits":
propertySchema.Pattern = "^\\d+$";
break;
case "Address":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidationAddress))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "Street":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
case "Location":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
if (context.JsonTypeInfo.Type == typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidationLocation))
{
foreach (var jsonProperty in context.JsonTypeInfo.Properties)
{
if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo || schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) || rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
switch (propertyInfo.Name)
{
case "PostalCode":
schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);
break;
}
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
private static global::System.Threading.Tasks.Task TransformOperationAsync(global::Microsoft.OpenApi.OpenApiOperation operation, global::Microsoft.AspNetCore.OpenApi.OpenApiOperationTransformerContext context, global::System.Threading.CancellationToken cancellationToken)
{
_ = cancellationToken;
foreach (var binding in context.Description.ParameterDescriptions)
{
if (binding.ModelMetadata?.ContainerType != typeof(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1CmdDto) || binding.ModelMetadata.PropertyName != "Id")
{
continue;
}
var parameter = operation.Parameters?.FirstOrDefault(candidate => candidate.Name == binding.Name);
if (parameter?.Schema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
AddInexact(propertySchema, "CustomValidationAttribute");
}
foreach (var binding in context.Description.ParameterDescriptions)
{
if (binding.ModelMetadata?.ContainerType != typeof(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1QueryDto) || binding.ModelMetadata.PropertyName != "Customer")
{
continue;
}
var parameter = operation.Parameters?.FirstOrDefault(candidate => candidate.Name == binding.Name);
if (parameter?.Schema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
ApplyMinimum(propertySchema, 2);
}
foreach (var binding in context.Description.ParameterDescriptions)
{
if (binding.ModelMetadata?.ContainerType != typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1CmdDto) || binding.ModelMetadata.PropertyName != "Body")
{
continue;
}
if (operation.RequestBody is global::Microsoft.OpenApi.OpenApiRequestBody requestBody)
{
requestBody.Required = true;
}
}
foreach (var binding in context.Description.ParameterDescriptions)
{
if (binding.ModelMetadata?.ContainerType != typeof(global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1CmdDto) || binding.ModelMetadata.PropertyName != "ValidationCode")
{
continue;
}
var parameter = operation.Parameters?.FirstOrDefault(candidate => candidate.Name == binding.Name);
if (parameter?.Schema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)
{
continue;
}
ApplyMinimum(propertySchema, 1);
}
return global::System.Threading.Tasks.Task.CompletedTask;
}
private static void ApplyMinimum(global::Microsoft.OpenApi.OpenApiSchema schema, int length)
{
    if ((schema.Type & global::Microsoft.OpenApi.JsonSchemaType.Array) != 0)
    {
        schema.MinItems = length;
        return;
    }
    schema.MinLength = length;
}
private static void ApplyMaximum(global::Microsoft.OpenApi.OpenApiSchema schema, int length)
{
    if ((schema.Type & global::Microsoft.OpenApi.JsonSchemaType.Array) != 0)
    {
        schema.MaxItems = length;
        return;
    }
    schema.MaxLength = length;
}
private static void AddInexact(global::Microsoft.OpenApi.OpenApiSchema schema, string rule)
{
    var text = "Expo validation rule: " + rule + ".";
    schema.Description = global::System.String.IsNullOrWhiteSpace(schema.Description)
        ? text : schema.Description + " " + text;
}}
