// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal static class BrigadeRoutes
{
    public static void Register(global::Brigade.Net.Partie.IPartieEngine engine)
    {engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2);
engine.Map(Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3);

}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value7) {
public global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
public global::Microsoft.AspNetCore.Http.HttpContext value2 { get; } = value2;
public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3 { get; } = value3;
public global::Brigade.Net.Example.Domain.Orders.IOrderStore value7 { get; } = value7;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.Create", new string[] { "/api/v1", "/orders", "" }, "POST", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
new("value2", "value2", typeof(global::Microsoft.AspNetCore.Http.HttpContext), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value3", "value3", typeof(global::Brigade.Net.Example.Domain.Orders.OrderRequestScope), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value7", "value7", typeof(global::Brigade.Net.Example.Domain.Orders.IOrderStore), global::Brigade.Net.Partie.PartieInputSource.Service),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(inputs.value0, inputs.value1, inputs.value2, inputs.value3, inputs.value7));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value7) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Example.Web.TraceOrderRequestPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Example.Web.TraceOrderContext, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>(new global::Brigade.Net.Example.Web.TraceOrderContext(value2, value3), value0, Next_value4, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>> Next_value4(global::Brigade.Net.Core.Results.Unit value4) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Example.Domain.ValidationPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Partie.EmptyContext, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>(new global::Brigade.Net.Partie.EmptyContext(), value0, Next_value5, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>> Next_value5(global::Brigade.Net.Core.Results.Unit value5) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Partie.UnitOfWorkPartie, global::Brigade.Net.Core.Transactions.UnitOfWork, global::Brigade.Net.Partie.UnitOfWorkContext, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>(new global::Brigade.Net.Partie.UnitOfWorkContext(new global::Brigade.Net.Core.Transactions.ITxn[] {  }), value0, Next_value6, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>> Next_value6(global::Brigade.Net.Core.Transactions.UnitOfWork value6) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result>>(global::Brigade.Net.Partie.RouteDispatch.Command<global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Handler, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Result, global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Context>(value6, new global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Context(value7, value3), value0, value1));
}
}
}
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0Dto {

[global::Microsoft.AspNetCore.Mvc.FromBody]
public required global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderPlacement @Body { get; set; }
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value7) {
public global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
public global::Microsoft.AspNetCore.Http.HttpContext value2 { get; } = value2;
public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3 { get; } = value3;
public global::Brigade.Net.Example.Domain.Orders.IOrderStore value7 { get; } = value7;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1, global::Brigade.Net.Core.Results.Unit> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.Delete", new string[] { "/api/v1", "/orders", "{id}" }, "DELETE", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
new("value2", "value2", typeof(global::Microsoft.AspNetCore.Http.HttpContext), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value3", "value3", typeof(global::Brigade.Net.Example.Domain.Orders.OrderRequestScope), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value7", "value7", typeof(global::Brigade.Net.Example.Domain.Orders.IOrderStore), global::Brigade.Net.Partie.PartieInputSource.Service),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(inputs.value0, inputs.value1, inputs.value2, inputs.value3, inputs.value7));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Core.Results.Unit>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value7) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Example.Web.TraceOrderRequestPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Example.Web.TraceOrderContext, global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd, global::Brigade.Net.Core.Results.Unit>(new global::Brigade.Net.Example.Web.TraceOrderContext(value2, value3), value0, Next_value4, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Core.Results.Unit>> Next_value4(global::Brigade.Net.Core.Results.Unit value4) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Example.Domain.ValidationPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Partie.EmptyContext, global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd, global::Brigade.Net.Core.Results.Unit>(new global::Brigade.Net.Partie.EmptyContext(), value0, Next_value5, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Core.Results.Unit>> Next_value5(global::Brigade.Net.Core.Results.Unit value5) {
return global::Brigade.Net.Partie.RouteDispatch.CommandPartie<global::Brigade.Net.Partie.UnitOfWorkPartie, global::Brigade.Net.Core.Transactions.UnitOfWork, global::Brigade.Net.Partie.UnitOfWorkContext, global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd, global::Brigade.Net.Core.Results.Unit>(new global::Brigade.Net.Partie.UnitOfWorkContext(new global::Brigade.Net.Core.Transactions.ITxn[] {  }), value0, Next_value6, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Core.Results.Unit>> Next_value6(global::Brigade.Net.Core.Transactions.UnitOfWork value6) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Core.Results.Unit>>(global::Brigade.Net.Partie.RouteDispatch.Command<global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Handler, global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Context>(value6, new global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Context(value7, value3), value0, value1));
}
}
}
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1Dto {

[global::Microsoft.AspNetCore.Mvc.FromRoute(Name = "id")]
public required global::System.Guid @Id { get; set; }
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value6) {
public global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
public global::Microsoft.AspNetCore.Http.HttpContext value2 { get; } = value2;
public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3 { get; } = value3;
public global::Brigade.Net.Example.Domain.Orders.IOrderStore value6 { get; } = value6;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.Search", new string[] { "/api/v1", "/orders", "" }, "GET", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
new("value2", "value2", typeof(global::Microsoft.AspNetCore.Http.HttpContext), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value3", "value3", typeof(global::Brigade.Net.Example.Domain.Orders.OrderRequestScope), global::Brigade.Net.Partie.PartieInputSource.Service),
new("value6", "value6", typeof(global::Brigade.Net.Example.Domain.Orders.IOrderStore), global::Brigade.Net.Partie.PartieInputSource.Service),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(inputs.value0, inputs.value1, inputs.value2, inputs.value3, inputs.value6));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value6) {
return global::Brigade.Net.Partie.RouteDispatch.QueryPartie<global::Brigade.Net.Example.Web.TraceOrderRequestPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Example.Web.TraceOrderContext, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>(new global::Brigade.Net.Example.Web.TraceOrderContext(value2, value3), value0, Next_value4, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>> Next_value4(global::Brigade.Net.Core.Results.Unit value4) {
return global::Brigade.Net.Partie.RouteDispatch.QueryPartie<global::Brigade.Net.Example.Domain.ValidationPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Partie.EmptyContext, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>(new global::Brigade.Net.Partie.EmptyContext(), value0, Next_value5, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>> Next_value5(global::Brigade.Net.Core.Results.Unit value5) {
return global::Brigade.Net.Partie.RouteDispatch.QueryPartie<global::Brigade.Net.Example.Domain.Orders.OrderProvider, global::Brigade.Net.Example.Domain.Orders.Order[], global::Brigade.Net.Example.Domain.Orders.OrderProviderContext, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>(new global::Brigade.Net.Example.Domain.Orders.OrderProviderContext(value6, value3), value0, Next_value7, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>> Next_value7(global::Brigade.Net.Example.Domain.Orders.Order[] value7) {
return global::Brigade.Net.Partie.RouteDispatch.QueryPartie<global::Brigade.Net.Example.Domain.Orders.OrderInspectionPartie, global::Brigade.Net.Core.Results.Unit, global::Brigade.Net.Example.Domain.Orders.OrderInspectionContext, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>(new global::Brigade.Net.Example.Domain.Orders.OrderInspectionContext(value7, value3), value0, Next_value8, value1);
global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>> Next_value8(global::Brigade.Net.Core.Results.Unit value8) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[]>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Handler, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query, global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Result[], global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Context>(new global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Context(value7, value3), value0, value1));
}
}
}
}
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2Dto {

[global::Microsoft.AspNetCore.Mvc.FromQuery(Name = "id")]
public global::System.Guid? @Id { get; set; } = default!;

[global::Microsoft.AspNetCore.Mvc.FromQuery(Name = "customer")]
public string? @Customer { get; set; } = default!;
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
public global::Brigade.Net.Partie.EmptyQuery value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0, string> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.PolicyTests.A", new string[] { "/api/v1", "/orders", "/policy-test", "a" }, "GET", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Partie.EmptyQuery), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0(inputs.value0, inputs.value1));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Partie.EmptyQuery, string, global::Brigade.Net.Partie.EmptyContext>(new global::Brigade.Net.Partie.EmptyContext(), value0, value1));
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_0Dto {
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
public global::Brigade.Net.Partie.EmptyQuery value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1, string> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.PolicyTests.B", new string[] { "/api/v1", "/orders", "/policy-test", "b" }, "GET", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Partie.EmptyQuery), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1(inputs.value0, inputs.value1));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Partie.EmptyQuery, string, global::Brigade.Net.Partie.EmptyContext>(new global::Brigade.Net.Partie.EmptyContext(), value0, value1));
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_1Dto {
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
public global::Brigade.Net.Partie.EmptyQuery value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2, string> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.PolicyTests.C", new string[] { "/api/v1", "/orders", "/policy-test", "c" }, "GET", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Partie.EmptyQuery), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(inputs.value0, inputs.value1));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Partie.EmptyQuery, string, global::Brigade.Net.Partie.EmptyContext>(new global::Brigade.Net.Partie.EmptyContext(), value0, value1));
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2Dto {
}
public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
public global::Brigade.Net.Partie.EmptyQuery value0 { get; } = value0;
public global::System.Threading.CancellationToken value1 { get; } = value1;
}
public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3, string> Route_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3 { get; } = new(
"Brigade.Net.Example.Web.Routing.Orders.PolicyTests.D", new string[] { "/api/v1", "/orders", "/policy-test", "d" }, "GET", new global::Brigade.Net.Partie.PartieInput[] {
new("request", "value0", typeof(global::Brigade.Net.Partie.EmptyQuery), global::Brigade.Net.Partie.PartieInputSource.Request),
new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation),
}, static inputs => Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(inputs.value0, inputs.value1));
private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(global::Brigade.Net.Partie.EmptyQuery value0, global::System.Threading.CancellationToken value1) {
return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Partie.EmptyQuery, string, global::Brigade.Net.Partie.EmptyContext>(new global::Brigade.Net.Partie.EmptyContext(), value0, value1));
}

public sealed class Inputs_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3Dto {
}

}