// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Orders
    {
        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Create(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Delete(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Search(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Validate(builder);
        }
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3(builder);
    }
}
