// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Orders
    {
        private static partial class PolicyTests
        {
            static partial void A()
            {
            }

            static partial void B()
            {
            }

            internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @C(builder);
            }

            internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @D(builder);
            }
        }

        internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            PolicyTests.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(builder);
        }

        internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            PolicyTests.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(builder);
        }
    }

    internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_2(builder);
    }

    internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f72646572732e506f6c6963795465737473_3(builder);
    }
}