// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Mise
    {
        private static partial class MySql
        {
            internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @SearchAccounts(builder);
            }

            internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @SearchPurchases(builder);
            }

            internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @UpdateAccount(builder);
            }
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            MySql.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_0(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            MySql.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_1(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            MySql.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_2(builder);
        }
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_0(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_1(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_002eMySql_2(builder);
    }
}
