// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class ResultCases
    {
        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Delete(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Search(builder);
        }
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        ResultCases.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_0(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        ResultCases.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eResultCases_1(builder);
    }
}
