// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Orders
    {
        internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Create(builder);
        }

        internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Delete(builder);
        }

        internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @Search(builder);
        }
    }

    internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_0(builder);
    }

    internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_1(builder);
    }

    internal static void Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_427269676164652e4e65742e4578616d706c652e5765622e526f7574696e672e4f7264657273_2(builder);
    }
}