// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal static partial class BrigadeRoutes
{
    public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0, string> Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0 { get; } = new("Brigade.Net.Example.Web.Routing.Orders.PolicyTests.A", new string[] { "/api/v1", "/orders", "/policy-test", "a" }, "GET", new global::Brigade.Net.Partie.PartieInput[] { new("request", "value0", typeof(global::Brigade.Net.Core.Results.Unit), global::Brigade.Net.Partie.PartieInputSource.Request), new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation), }, static inputs => Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0(inputs.value0, inputs.value1));

    private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0(global::Brigade.Net.Core.Results.Unit value0, global::System.Threading.CancellationToken value1)
    {
        return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Core.Results.Unit, string, global::Brigade.Net.Core.Results.Unit>(global::Brigade.Net.Core.Results.Unit.Default, value0, value1));
    }

    public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1, string> Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1 { get; } = new("Brigade.Net.Example.Web.Routing.Orders.PolicyTests.B", new string[] { "/api/v1", "/orders", "/policy-test", "b" }, "GET", new global::Brigade.Net.Partie.PartieInput[] { new("request", "value0", typeof(global::Brigade.Net.Core.Results.Unit), global::Brigade.Net.Partie.PartieInputSource.Request), new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation), }, static inputs => Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1(inputs.value0, inputs.value1));

    private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1(global::Brigade.Net.Core.Results.Unit value0, global::System.Threading.CancellationToken value1)
    {
        return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Core.Results.Unit, string, global::Brigade.Net.Core.Results.Unit>(global::Brigade.Net.Core.Results.Unit.Default, value0, value1));
    }

    public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2, string> Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2 { get; } = new("Brigade.Net.Example.Web.Routing.Orders.PolicyTests.C", new string[] { "/api/v1", "/orders", "/policy-test", "c" }, "GET", new global::Brigade.Net.Partie.PartieInput[] { new("request", "value0", typeof(global::Brigade.Net.Core.Results.Unit), global::Brigade.Net.Partie.PartieInputSource.Request), new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation), }, static inputs => Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(inputs.value0, inputs.value1));

    private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(global::Brigade.Net.Core.Results.Unit value0, global::System.Threading.CancellationToken value1)
    {
        return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Core.Results.Unit, string, global::Brigade.Net.Core.Results.Unit>(global::Brigade.Net.Core.Results.Unit.Default, value0, value1));
    }

    public static global::Brigade.Net.Partie.PartieRoute<Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3, string> Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3 { get; } = new("Brigade.Net.Example.Web.Routing.Orders.PolicyTests.D", new string[] { "/api/v1", "/orders", "/policy-test", "d" }, "GET", new global::Brigade.Net.Partie.PartieInput[] { new("request", "value0", typeof(global::Brigade.Net.Core.Results.Unit), global::Brigade.Net.Partie.PartieInputSource.Request), new("cancellationToken", "value1", typeof(global::System.Threading.CancellationToken), global::Brigade.Net.Partie.PartieInputSource.Cancellation), }, static inputs => Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(inputs.value0, inputs.value1));

    private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>> Execute_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(global::Brigade.Net.Core.Results.Unit value0, global::System.Threading.CancellationToken value1)
    {
        return new global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<string>>(global::Brigade.Net.Partie.RouteDispatch.Query<global::Brigade.Net.Example.Domain.PolicyTesting.TestPolicyHandler, global::Brigade.Net.Core.Results.Unit, string, global::Brigade.Net.Core.Results.Unit>(global::Brigade.Net.Core.Results.Unit.Default, value0, value1));
    }
}
