// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Mise
    {
        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchAccountsMariaDb(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchAccountsMySql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchAccountsPostgreSql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchAccountsSqlServer(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_4(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchAccountsSqlite(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_5(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchOrdersMariaDb(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_6(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchOrdersMySql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_7(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchOrdersPostgreSql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_8(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchOrdersSqlServer(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_9(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @SearchOrdersSqlite(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_10(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @UpdateAccountMariaDb(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_11(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @UpdateAccountMySql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_12(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @UpdateAccountPostgreSql(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_13(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @UpdateAccountSqlServer(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_14(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            @UpdateAccountSqlite(builder);
        }
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_0(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_0(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_1(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_1(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_2(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_3(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_4(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_4(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_5(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_5(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_6(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_6(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_7(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_7(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_8(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_8(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_9(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_9(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_10(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_10(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_11(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_11(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_12(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_12(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_13(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_13(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_14(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Mise.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eMise_14(builder);
    }
}
