// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web;
public static partial class Routing
{
    private static partial class Orders
    {
        private static partial class PolicyTests
        {
            static partial void A()
            {
            }

            static partial void B()
            {
            }

            internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @C(builder);
            }

            internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
            {
                @D(builder);
            }
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            PolicyTests.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(builder);
        }

        internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
        {
            PolicyTests.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(builder);
        }
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(builder);
    }

    internal static void Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
    {
        Orders.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(builder);
    }
}
