// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal sealed class Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpResponse value2, global::Microsoft.AspNetCore.Http.HttpContext value7, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value8, global::Brigade.Net.Example.Domain.Orders.IOrderStore value10)
{
    public global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd value0 { get; } = value0;
    public global::System.Threading.CancellationToken value1 { get; } = value1;
    public global::Microsoft.AspNetCore.Http.HttpResponse value2 { get; } = value2;
    public global::Microsoft.AspNetCore.Http.HttpContext value7 { get; } = value7;
    public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value8 { get; } = value8;
    public global::Brigade.Net.Example.Domain.Orders.IOrderStore value10 { get; } = value10;
}
