// TODO: CHECK
﻿// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal sealed class Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1(global::Brigade.Net.Core.Results.Unit value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpResponse value2)
{
    public global::Brigade.Net.Core.Results.Unit value0 { get; } = value0;
    public global::System.Threading.CancellationToken value1 { get; } = value1;
    public global::Microsoft.AspNetCore.Http.HttpResponse value2 { get; } = value2;
}
