// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal sealed class Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value7)
{
    public global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd value0 { get; } = value0;
    public global::System.Threading.CancellationToken value1 { get; } = value1;
    public global::Microsoft.AspNetCore.Http.HttpContext value2 { get; } = value2;
    public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3 { get; } = value3;
    public global::Brigade.Net.Example.Domain.Orders.IOrderStore value7 { get; } = value7;
}
