// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Generated;
internal sealed class Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, global::Brigade.Net.Example.Domain.Orders.IOrderStore value6)
{
    public global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query value0 { get; } = value0;
    public global::System.Threading.CancellationToken value1 { get; } = value1;
    public global::Microsoft.AspNetCore.Http.HttpContext value2 { get; } = value2;
    public global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3 { get; } = value3;
    public global::Brigade.Net.Example.Domain.Orders.IOrderStore value6 { get; } = value6;
}
