// <auto-generated />
#nullable enable
namespace Microsoft.AspNetCore.Builder;
internal static class PartieRoutingExtensions
{
    public static global::Microsoft.AspNetCore.Builder.WebApplication UsePartieRoutes(this global::Microsoft.AspNetCore.Builder.WebApplication app)
    {
        var Group_Brigade_002eNet_002eExample_002eWeb_002eRouting = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(app, "/api/v1");
        var Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting, "/orders");
        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders, "", new[] { "POST" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1CmdDto value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.IOrderStore value6) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(new global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderCreateV1Cmd { @Body = value0.@Body }, value1, value2, value3, value6))), "Brigade.Net.Example.Web.Routing.Orders.Create");
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_0(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders, "/{orderId}", new[] { "DELETE" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1CmdDto value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.IOrderStore value6) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(new global::Brigade.Net.Example.Domain.Orders.DeleteV1.OrderDeleteV1Cmd { @Id = value0.@Id }, value1, value2, value3, value6))), "Brigade.Net.Example.Web.Routing.Orders.Delete");
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_1(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders, "", new[] { "GET" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1QueryDto value0, global::System.Threading.CancellationToken value1, global::Microsoft.AspNetCore.Http.HttpContext value2, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.OrderRequestScope value3, [global::Microsoft.AspNetCore.Mvc.FromServices] global::Brigade.Net.Example.Domain.Orders.IOrderStore value5) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(new global::Brigade.Net.Example.Domain.Orders.SearchV1.OrderSearchV1Query { @Id = value0.@Id, @Customer = value0.@Customer }, value1, value2, value3, value5))), "Brigade.Net.Example.Web.Routing.Orders.Search");
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_2(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders, "/validate", new[] { "POST" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1CmdDto value0, global::System.Threading.CancellationToken value1) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3(new global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Cmd { @Body = value0.@Body }, value1))), "Brigade.Net.Example.Web.Routing.Orders.Validate");
            global::Brigade.Net.Partie.Extensions.Expo.ExpoValidationRoutePolicy<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Cmd>.Command(__routeBuilder);
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_3(__routeBuilder);
        }

        var Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGroup(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders, "/policy-test");
        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests, "/a", new[] { "GET" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Partie.Generated.UnitDto value0, global::System.Threading.CancellationToken value1) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_0(new global::Brigade.Net.Core.Results.Unit { }, value1))), "Brigade.Net.Example.Web.Routing.Orders.PolicyTests.A");
            global::Brigade.Net.Example.Web.RoutePolicies.FakeHeaderCheckRoutePolicy<global::Brigade.Net.Core.Results.Unit>.Query(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests, "/b", new[] { "GET" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Partie.Generated.UnitDto value0, global::System.Threading.CancellationToken value1) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_1(new global::Brigade.Net.Core.Results.Unit { }, value1))), "Brigade.Net.Example.Web.Routing.Orders.PolicyTests.B");
            global::Brigade.Net.Example.Web.RoutePolicies.FakeAuthorizationRoutePolicy<global::Brigade.Net.Core.Results.Unit>.Query(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests, "/c", new[] { "GET" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Partie.Generated.UnitDto value0, global::System.Threading.CancellationToken value1) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(new global::Brigade.Net.Core.Results.Unit { }, value1))), "Brigade.Net.Example.Web.Routing.Orders.PolicyTests.C");
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_2(__routeBuilder);
        }

        {
            var __routeBuilder = global::Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithName(global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests, "/d", new[] { "GET" }, static ([global::Microsoft.AspNetCore.Http.AsParameters] global::Brigade.Net.Partie.Generated.UnitDto value0, global::System.Threading.CancellationToken value1) => global::Brigade.Net.Partie.Generated.BrigadeRoutes.Route_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3.ExecuteAsync(new global::Brigade.Net.Partie.Generated.Inputs_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(new global::Brigade.Net.Core.Results.Unit { }, value1))), "Brigade.Net.Example.Web.Routing.Orders.PolicyTests.D");
            global::Brigade.Net.Example.Web.Routing.Configure_Group_Brigade_002eNet_002eExample_002eWeb_002eRouting_002eOrders_002ePolicyTests_3(__routeBuilder);
        }

        return app;
    }
}
