// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Mise.MariaDb;
[global::Brigade.Net.Partie.BundleRegistration(typeof(global::Brigade.Net.Partie.Extensions.Mise.MariaDb.MiseMariaDbBundle<, >))]
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @MiseMariaDbBundleAttribute([global::Brigade.Net.Partie.Parameter] string @ConnectionStringName) : global::System.Attribute
{
    public string @ConnectionStringName { get; } = @ConnectionStringName;
}
