// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.SearchV1;
public sealed class OrderSearchV1QueryDto
{
    [global::Microsoft.AspNetCore.Mvc.FromQuery(Name = "orderId")]
    public global::System.Guid? @Id { get; set; } = default!;

    [global::Microsoft.AspNetCore.Mvc.FromQuery(Name = "customer")]
    public string? @Customer { get; set; } = default!;
}
