// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.CreateV1;
public sealed class OrderCreateV1CmdDto
{
    [global::Microsoft.AspNetCore.Mvc.FromBody]
    public required global::Brigade.Net.Example.Domain.Orders.CreateV1.OrderPlacement @Body { get; set; }
}
