// TODO: CHECK
﻿// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Example.Domain.ValidationPartie<, >), false)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @ValidationPartieAttribute() : global::System.Attribute
{
}
