// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.ResultCases.SearchV1;
public sealed class ResultCaseSearchV1QueryDto
{
    [global::Microsoft.AspNetCore.Mvc.FromQuery]
    public required string @Case { get; set; }
}
