namespace Brigade.Net.Mise;

/// <summary>Marks a mapped value as generated by the database when inserted.</summary>
[AttributeUsage(AttributeTargets.Property, Inherited = true)]
public sealed class DatabaseGeneratedAttribute : Attribute;
