using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Brigade.Net.Partie.Generator;

public static class BrigadeGeneratorCore
{
    private static readonly DiagnosticDescriptor InvalidRoute = new(
        "BRG005", "Invalid Brigade route", "{0}", "Brigade.Routing", DiagnosticSeverity.Error, true
    );

    public static void Initialize(
        IncrementalGeneratorInitializationContext context,
        Func<RouteEmission, string>? emitRoute = null,
        Func<string, string>? emitAdapter = null,
        Func<AttributeData, RouteDeclaration?>? discoverRoute = null
    )
    {
        var groups = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Brigade.Net.Partie.BrigadeGroupAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            (attributeContext, cancellationToken) => BuildGroup(attributeContext, cancellationToken, emitRoute, discoverRoute)
        ).WithTrackingName("BrigadeGroups");

        context.RegisterSourceOutput(groups, static (output, group) =>
        {
            foreach (var diagnostic in group.Diagnostics)
            {
                output.ReportDiagnostic(diagnostic);
            }

            if (group.Stubs.Length != 0)
            {
                output.AddSource(group.Source.Key + ".Routes.g.cs", group.Stubs);
            }
        });

        var sources = groups.Select(static (group, _) => group.Source).WithTrackingName("BrigadeRouteSources");
        context.RegisterSourceOutput(sources.Collect(), (output, groups) =>
        {
            var registrations = new StringBuilder();
            var members = new StringBuilder();
            var adapter = new StringBuilder();
            foreach (var group in groups.OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                registrations.Append(group.Registrations);
                members.Append(group.Members);
                adapter.Append(group.Adapter);
            }

            output.AddSource("BrigadeRoutes.g.cs", """
                // <auto-generated />
                #nullable enable
                namespace Brigade.Net.Partie.Generated;
                internal static class BrigadeRoutes
                {
                    public static void Register(global::Brigade.Net.Partie.IPartieEngine engine)
                    {
                """ + registrations + "\n}\n" + members + "\n}");
            if (emitAdapter is not null)
            {
                output.AddSource("PartieEngine.g.cs", emitAdapter(adapter.ToString()));
            }
        });
    }

    private static GroupOutput BuildGroup(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken,
        Func<RouteEmission, string>? emitRoute,
        Func<AttributeData, RouteDeclaration?>? discoverRoute
    )
    {
        var group = (INamedTypeSymbol)context.TargetSymbol;
        var declaration = (ClassDeclarationSyntax)context.TargetNode;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var registrations = new StringBuilder();
        var members = new StringBuilder();
        var adapter = new StringBuilder();
        var stubs = new List<MemberDeclarationSyntax>();
        var key = "Group_" + string.Concat(Encoding.UTF8.GetBytes(group.ToDisplayString()).Select(value => value.ToString("x2")));

        if (group.ContainingType is not null || group.Arity != 0 || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)
            || declaration.Modifiers.Any(SyntaxKind.FileKeyword))
        {
            Report(group, "Route groups must be top-level, non-generic, non-file-local partial classes");
            return Finish("");
        }

        var prefix = context.Attributes[0].ConstructorArguments[0].Value as string ?? "";
        var providerAttributes = group.GetAttributes().Where(attribute => IsAttribute(attribute, "ProviderAttribute")).ToArray();
        var routeIndex = 0;
        foreach (var route in group.GetMembers().OfType<IMethodSymbol>().OrderBy(method => method.Name, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var attributes = route.GetAttributes();
            var routes = attributes.Select(attribute => IsAttribute(attribute, "RouteAttribute")
                ? new RouteDeclaration(
                    attribute.ConstructorArguments[0].Value as string ?? "",
                    attribute.ConstructorArguments[1].Value as string ?? ""
                )
                : discoverRoute?.Invoke(attribute)).Where(route => route is not null).ToArray();
            var handlers = attributes.Where(attribute => IsAttribute(attribute, "HandlerAttribute")).ToArray();
            if (routes.Length == 0 && handlers.Length == 0)
            {
                continue;
            }

            var syntax = route.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(cancellationToken) as MethodDeclarationSyntax;
            if (!route.IsStatic || route.Arity != 0 || route.Parameters.Length != 0 || !route.ReturnsVoid
                || syntax is null || !syntax.Modifiers.Any(SyntaxKind.PartialKeyword)
                || syntax.Body is not null || syntax.ExpressionBody is not null || route.PartialImplementationPart is not null)
            {
                Report(route, "Route declarations must be unimplemented static partial void methods without type parameters or arguments");
                continue;
            }

            stubs.Add(syntax.WithAttributeLists(default).WithBody(SyntaxFactory.Block()).WithSemicolonToken(default));
            if (routes.Length != 1 || handlers.Length != 1)
            {
                Report(route, "Each route must declare exactly one route attribute and one Handler");
                continue;
            }

            var handler = GetMethod(GetRegisteredType(handlers[0]), route);
            var parties = attributes.Where(attribute => IsAttribute(attribute, "PartieAttribute"))
                .Select(attribute => GetMethod(GetRegisteredType(attribute), route)).ToArray();
            var providers = providerAttributes.Concat(attributes.Where(attribute => IsAttribute(attribute, "ProviderAttribute")))
                .Select(GetRegisteredType).ToArray();
            if (handler is null || parties.Any(method => method is null) || providers.Any(type => type is null))
            {
                Report(route, "Route types must resolve to named Handler, Partie and Provider types");
                continue;
            }

            var planned = new RouteGraphPlanner(context.SemanticModel.Compilation).Plan(
                handler, parties.Select(method => method!), providers.Select(type => type!), cancellationToken
            );
            diagnostics.AddRange(planned.Diagnostics);
            if (planned.Graph is not { } graph)
            {
                continue;
            }

            var pattern = string.Join("/", new[] { prefix.TrimEnd('/'), routes[0]!.Pattern.TrimStart('/') }
                .Where(part => part.Length != 0));
            var operation = routes[0]!.Operation;
            if (string.IsNullOrWhiteSpace(operation))
            {
                Report(route, "A route operation must not be empty");
                continue;
            }

            var bindings = graph.ExternalValues.Select(value => RouteInputBinding.Read(value.ExternalParameter!).FirstOrDefault()
                ?? new RouteInputBinding(
                    value.Type.ToDisplayString() == "System.Threading.CancellationToken" ? "Cancellation" : "Service",
                    value.ExternalParameter!.Name
                )).ToArray();
            var bodyCount = bindings.Count(binding => binding.Source == "Body");
            if (bodyCount > 1 || (bodyCount != 0 && operation.Equals("GET", StringComparison.OrdinalIgnoreCase)))
            {
                Report(route, "GET routes cannot bind a body; other routes may bind at most one body value");
                continue;
            }

            var suffix = key + "_" + routeIndex++;
            var inputName = "Inputs_" + suffix;
            var executeName = "Execute_" + suffix;
            var descriptorName = "Route_" + suffix;
            var inputParameters = graph.ExternalValues.Select(value => TypeName(value.Type) + " value" + value.Id).ToArray();
            members.Append("public sealed class ").Append(inputName).Append('(').Append(string.Join(", ", inputParameters)).Append(") {\n");
            foreach (var value in graph.ExternalValues)
            {
                members.Append("public ").Append(TypeName(value.Type)).Append(" value").Append(value.Id)
                    .Append(" { get; } = value").Append(value.Id).Append(";\n");
            }

            members.Append("}\npublic static global::Brigade.Net.Partie.PartieRoute<").Append(inputName).Append(", ")
                .Append(TypeName(graph.ResultType)).Append("> ").Append(descriptorName).Append(" { get; } = new(\n")
                .Append(Literal(group.ToDisplayString() + "." + route.Name)).Append(", ").Append(Literal(pattern)).Append(", ")
                .Append(Literal(operation)).Append(", new global::Brigade.Net.Partie.PartieInput[] {\n");
            for (var index = 0; index < graph.ExternalValues.Length; index++)
            {
                var value = graph.ExternalValues[index];
                var binding = bindings[index];
                members.Append("new(").Append(Literal(binding.Name)).Append(", ").Append(Literal("value" + value.Id))
                    .Append(", typeof(").Append(value.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append("), global::Brigade.Net.Partie.PartieInputSource.")
                    .Append(binding.Source).Append("),\n");
            }

            members.Append("}, static inputs => ").Append(executeName).Append('(')
                .Append(string.Join(", ", graph.ExternalValues.Select(value => "inputs.value" + value.Id))).Append("));\n")
                .AppendLine(RoutePipelineEmitter.Emit(graph, executeName));
            registrations.Append("engine.Map(").Append(descriptorName).Append(");\n");
            if (emitRoute is not null)
            {
                adapter.Append(emitRoute(new RouteEmission(
                    group.ToDisplayString() + "." + route.Name,
                    pattern,
                    operation,
                    "global::Brigade.Net.Partie.Generated.BrigadeRoutes." + descriptorName,
                    "global::Brigade.Net.Partie.Generated.BrigadeRoutes." + inputName,
                    graph.ExternalValues.Select((value, index) => new RouteInputEmission(
                        TypeName(value.Type), "value" + value.Id, bindings[index].Name, bindings[index].Source
                    )).ToImmutableArray()
                )));
            }
        }

        var stubClass = declaration.WithAttributeLists(default).WithBaseList(null)
            .WithParameterList(null).WithMembers(SyntaxFactory.List(stubs));
        var stubSource = stubClass.NormalizeWhitespace().ToFullString();
        if (!group.ContainingNamespace.IsGlobalNamespace)
        {
            stubSource = "namespace " + group.ContainingNamespace.ToDisplayString() + ";\n" + stubSource;
        }

        return Finish("// <auto-generated />\n#nullable enable\n" + stubSource);

        void Report(ISymbol symbol, string message) => diagnostics.Add(Diagnostic.Create(InvalidRoute, symbol.Locations.FirstOrDefault(), message));

        IMethodSymbol? GetMethod(INamedTypeSymbol? type, ISymbol owner)
        {
            var candidates = type?.GetMembers("InvokeAsync").OfType<IMethodSymbol>().ToArray();
            if (candidates is null || candidates.Length != 1 || type!.IsUnboundGenericType)
            {
                Report(owner, "Handler and route Partie types must be closed and declare exactly one InvokeAsync method");
                return null;
            }

            return candidates[0];
        }

        GroupOutput Finish(string stubSource) => new(
            stubSource, new GroupSource(key, registrations.ToString(), members.ToString(), adapter.ToString()), diagnostics.ToImmutable()
        );
    }

    private static bool IsAttribute(AttributeData attribute, string name) =>
        attribute.AttributeClass?.ContainingNamespace.ToDisplayString() == "Brigade.Net.Partie"
        && attribute.AttributeClass.Name == name;

    private static INamedTypeSymbol? GetRegisteredType(AttributeData attribute) =>
        attribute.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol;

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(
        SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier)
    );
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private sealed class GroupSource(string key, string registrations, string members, string adapter) : IEquatable<GroupSource>
    {
        public string Key { get; } = key;
        public string Registrations { get; } = registrations;
        public string Members { get; } = members;
        public string Adapter { get; } = adapter;
        public bool Equals(GroupSource? other) => other is not null && Key == other.Key && Registrations == other.Registrations && Members == other.Members && Adapter == other.Adapter;
        public override bool Equals(object? obj) => obj is GroupSource other && Equals(other);
        public override int GetHashCode() => Key.GetHashCode();
    }

    private sealed class GroupOutput(string stubs, GroupSource source, ImmutableArray<Diagnostic> diagnostics)
    {
        public string Stubs { get; } = stubs;
        public GroupSource Source { get; } = source;
        public ImmutableArray<Diagnostic> Diagnostics { get; } = diagnostics;
    }
}