using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Brigade.Net.Partie.Generator;

public static class BrigadeGeneratorCore
{
    private static readonly DiagnosticDescriptor InvalidRoute = new("BRG005", "Invalid Brigade route", "{0}", "Brigade.Routing", DiagnosticSeverity.Error, true);
    public static void Initialize(
        IncrementalGeneratorInitializationContext context,
        Func<RouteEmission, string>? emitRoute = null,
        Func<string, string>? emitAdapter = null,
        Func<AttributeData, RouteDeclaration?>? discoverRoute = null,
        Func<IMethodSymbol, string, Compilation, Action<ISymbol, string>, ImmutableArray<RoutePolicyEmission>>? discoverPolicies = null,
        Func<IMethodSymbol, bool>? discoverPolicyFunctions = null,
        Func<RouteEmission, string>? emitTypes = null,
        Func<RouteGroupEmission, string>? emitGroup = null
    )
    {
        var groups = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Brigade.Net.Partie.BrigadeGroupAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            (attributeContext, cancellationToken) => BuildGroup(
                attributeContext,
                cancellationToken,
                emitRoute,
                discoverRoute,
                discoverPolicies,
                discoverPolicyFunctions,
                emitTypes
            )
        ).WithTrackingName("BrigadeGroups");
        context.RegisterSourceOutput(
            groups,
            static (output, group) =>
        {
            foreach (var diagnostic in group.Diagnostics)
            {
                output.ReportDiagnostic(diagnostic);
            }

            if (group.Stubs.Length != 0)
            {
                output.AddSource(group.Source.Key + ".Routes.g.cs", group.Stubs);
            }
        }
        );
        var sources = groups.Select(static (group, _) => group.Source).WithTrackingName("BrigadeRouteSources");
        context.RegisterSourceOutput(
            sources.Collect(),
            (output, groups) =>
        {
            var registrations = new StringBuilder();
            var members = new StringBuilder();
            var adapter = new StringBuilder();
            foreach (var group in groups.OrderBy(group => group.Groups.Length).ThenBy(group => group.Key, StringComparer.Ordinal))
            {
                registrations.Append(group.Registrations);
                members.Append(group.Members);
                if (emitGroup is not null && group.Groups.Length != 0)
                {
                    adapter.Append(emitGroup(group.Groups[group.Groups.Length - 1]));
                }
                adapter.Append(group.Adapter);
            }

            output.AddSource(
                    "BrigadeRoutes.g.cs",
                    """
                // <auto-generated />
                #nullable enable
                namespace Brigade.Net.Partie.Generated;
                internal static class BrigadeRoutes
                {
                    public static void Register(global::Brigade.Net.Partie.IPartieEngine engine)
                    {
                """ + registrations + "\n}\n" + members + "\n}"
                );
            if (emitAdapter is not null)
            {
                output.AddSource("PartieEngine.g.cs", emitAdapter(adapter.ToString()));
            }
        }
        );
    }

    private static GroupOutput BuildGroup(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken,
        Func<RouteEmission, string>? emitRoute,
        Func<AttributeData, RouteDeclaration?>? discoverRoute,
        Func<IMethodSymbol, string, Compilation, Action<ISymbol, string>, ImmutableArray<RoutePolicyEmission>>? discoverPolicies,
        Func<IMethodSymbol, bool>? discoverPolicyFunctions,
        Func<RouteEmission, string>? emitTypes
    )
    {
        var group = (INamedTypeSymbol)context.TargetSymbol;
        var declaration = (ClassDeclarationSyntax)context.TargetNode;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var registrations = new StringBuilder();
        var members = new StringBuilder();
        var adapter = new StringBuilder();
        var stubs = new List<MemberDeclarationSyntax>();
        var policyWrappers = new List<(string Name, string ParameterType)>();
        var key = GroupKey(group);
        var hierarchy = ImmutableArray<RouteGroupEmission>.Empty;
        var outermost = group;
        for (INamedTypeSymbol? current = group; current is not null; current = current.ContainingType)
        {
            if (current.Arity != 0 || current.DeclaringSyntaxReferences.Any(reference =>
                reference.GetSyntax(cancellationToken) is not ClassDeclarationSyntax type
                || !type.Modifiers.Any(SyntaxKind.PartialKeyword) || type.Modifiers.Any(SyntaxKind.FileKeyword)))
            {
                Report(current, "Route groups and their containing types must be non-generic, non-file-local partial classes");
                return Finish("");
            }
            outermost = current;
        }

        var groupSymbols = RouteGroupHierarchy.GetGroups(group);
        foreach (var symbol in groupSymbols)
        {
            if (symbol.GetAttributes().First(RouteGroupHierarchy.IsGroup).ConstructorArguments[0].IsNull)
            {
                Report(symbol, "A group path must be a string array; use an empty array for a group with no path components");
                return Finish("");
            }
        }
        hierarchy = groupSymbols.Select((symbol, index) => new RouteGroupEmission(
            GroupKey(symbol),
            symbol.ToDisplayString(),
            index == 0 ? null : GroupKey(groupSymbols[index - 1]),
            symbol.GetAttributes().First(RouteGroupHierarchy.IsGroup).ConstructorArguments[0].Values
                .Select(component => component.Value as string ?? "").ToImmutableArray()
        )).ToImmutableArray();
        var providerAttributes = groupSymbols.SelectMany(symbol => symbol.GetAttributes())
            .Where(attribute => IsAttribute(attribute, "ProviderAttribute")).ToArray();
        var routeIndex = 0;
        foreach (var route in group.GetMembers().OfType<IMethodSymbol>().OrderBy(method => method.Name, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var attributes = route.GetAttributes();
            var routes = attributes.Select(
                attribute => IsAttribute(attribute, "RouteAttribute") ? new RouteDeclaration(
                    new[] { attribute.ConstructorArguments[0].Value as string ?? "" },
                    attribute.ConstructorArguments[1].Value as string ?? ""
                ) : discoverRoute?.Invoke(attribute)
            ).Where(route => route is not null).ToArray();
            var handlers = attributes.Where(attribute => IsAttribute(attribute, "HandlerAttribute")).ToArray();
            if (routes.Length == 0 && handlers.Length == 0)
            {
                continue;
            }

            var syntax = route.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(cancellationToken) as MethodDeclarationSyntax;
            var hasPolicyFunction = emitRoute is not null && discoverPolicyFunctions?.Invoke(route) == true;
            var isValidPolicyFunction = hasPolicyFunction && syntax is not null && (syntax.Body is not null || syntax.ExpressionBody is not null) && route.PartialImplementationPart is null;
            var isValidBasicRoute = route.Parameters.Length == 0 && syntax is not null && syntax.Modifiers.Any(SyntaxKind.PartialKeyword) && syntax.Body is null && syntax.ExpressionBody is null && route.PartialImplementationPart is null;
            if (!route.IsStatic || route.IsAsync || route.Arity != 0 || !route.ReturnsVoid || syntax is null || (!isValidBasicRoute && !isValidPolicyFunction))
            {
                Report(
                    route,
                    "Route declarations must be unimplemented static partial void methods without arguments, or implemented static void methods with an engine-supported configuration parameter; neither may be async or generic"
                );
                continue;
            }

            if (!hasPolicyFunction)
            {
                stubs.Add(
                    syntax.WithAttributeLists(default).WithBody(SyntaxFactory.Block()).WithSemicolonToken(default)
                );
            }
            else if (syntax.Modifiers.Any(SyntaxKind.PartialKeyword) && route.PartialDefinitionPart is null)
            {
                var parameter = syntax.ParameterList.Parameters[0].WithAttributeLists(default).WithType(SyntaxFactory.ParseTypeName(TypeName(route.Parameters[0].Type)));
                stubs.Add(
                    syntax.WithAttributeLists(default).WithBody(null).WithExpressionBody(null).WithParameterList(SyntaxFactory.ParameterList(SyntaxFactory.SingletonSeparatedList(parameter))).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                );
            }

            if (routes.Length != 1 || handlers.Length != 1)
            {
                Report(route, "Each route must declare exactly one route attribute and one Handler");
                continue;
            }

            var handler = GetRegisteredType(handlers[0]);
            var parties = attributes.Where(attribute => IsAttribute(attribute, "PartieAttribute")).Select(GetRegisteredType).ToArray();
            var providers = providerAttributes.Concat(attributes.Where(attribute => IsAttribute(attribute, "ProviderAttribute"))).Select(GetRegisteredType).ToArray();
            if (handler is null || parties.Any(method => method is null) || providers.Any(type => type is null))
            {
                Report(route, "Route types must resolve to named Handler, Partie and Provider types");
                continue;
            }

            var path = hierarchy.SelectMany(scope => scope.Path).Concat(routes[0]!.Path).ToImmutableArray();
            var operation = routes[0]!.Operation;
            if (string.IsNullOrWhiteSpace(operation))
            {
                Report(route, "A route operation must not be empty");
                continue;
            }

            var diagnosticCount = diagnostics.Count;
            var routePolicies = discoverPolicies?.Invoke(route, operation, context.SemanticModel.Compilation, Report) ?? ImmutableArray<RoutePolicyEmission>.Empty;
            if (diagnostics.Count != diagnosticCount)
            {
                continue;
            }

            var graph = new ContractPipelinePlanner(
                context.SemanticModel.Compilation,
                (
                    symbol,
                    message,
                    id
                ) => diagnostics.Add(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id,
                            "Invalid routing contract",
                            "{0}",
                            "Brigade.Routing",
                            DiagnosticSeverity.Error,
                            true
                        ),
                        symbol.Locations.FirstOrDefault(),
                        message
                    )
                ),
                cancellationToken
            ).Plan(handler, parties.Select(type => type!), providers.Select(type => type!), operation);
            if (graph is null)
            {
                continue;
            }

            var payloads = graph.Request.Properties.Where(property => property.Source is "Body" or "Form").ToArray();
            if (payloads.Count(property => property.Source == "Body") > 1 || (payloads.Any(property => property.Source == "Body") && payloads.Any(property => property.Source == "Form")) || (payloads.Length != 0 && operation.Equals("GET", StringComparison.OrdinalIgnoreCase)))
            {
                Report(
                    route,
                    "GET cannot bind a payload; only one JSON body is allowed and JSON cannot mix with form fields."
                );
                continue;
            }

            var suffix = key + "_" + routeIndex++;
            var routeName = group.GetMembers(route.Name).OfType<IMethodSymbol>().Skip(1).Any()
                ? route.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                : group.ToDisplayString() + "." + route.Name;
            var inputName = "Inputs_" + suffix;
            var executeName = "Execute_" + suffix;
            var descriptorName = "Route_" + suffix;
            var inputParameters = graph.Inputs.Select(input => input.TypeName + " " + input.MemberName).ToArray();
            members.Append("public sealed class ").Append(inputName).Append('(').Append(string.Join(", ", inputParameters)).Append(") {\n");
            foreach (var input in graph.Inputs)
            {
                members.Append("public ").Append(input.TypeName).Append(' ').Append(input.MemberName).Append(" { get; } = ").Append(input.MemberName).Append(";\n");
            }

            members.Append("}\npublic static global::Brigade.Net.Partie.PartieRoute<").Append(inputName).Append(", ").Append(graph.ResultType).Append("> ").Append(descriptorName).Append(" { get; } = new(\n").Append(Literal(routeName)).Append(", new string[] { ").Append(string.Join(", ", path.Select(Literal))).Append(" }, ").Append(Literal(operation)).Append(", new global::Brigade.Net.Partie.PartieInput[] {\n");
            foreach (var input in graph.Inputs)
            {
                members.Append("new(").Append(Literal(input.BindingName)).Append(", ").Append(Literal(input.MemberName)).Append(", typeof(").Append(input.RuntimeTypeName).Append("), global::Brigade.Net.Partie.PartieInputSource.").Append(input.Source).Append("),\n");
            }

            members.Append("}, static inputs => ").Append(executeName).Append('(').Append(string.Join(", ", graph.Inputs.Select(input => "inputs." + input.MemberName))).Append("));\n").Append(
                "private static global::System.Threading.Tasks.ValueTask<global::Brigade.Net.Core.Results.Result<"
            ).Append(graph.ResultType).Append(">> ").Append(executeName).Append('(').Append(string.Join(", ", inputParameters)).Append(") {\n").Append(graph.Body).Append("\n}\n");
            registrations.Append("engine.Map(").Append(descriptorName).Append(");\n");
            if (emitRoute is not null)
            {
                var policyFunctionName = "Configure_" + suffix;
                var policyFunctionFullName = TypeName(outermost) + "." + policyFunctionName;
                if (hasPolicyFunction)
                {
                    var parameterType = TypeName(route.Parameters[0].Type);
                    policyWrappers.Add((policyFunctionName, parameterType));
                    stubs.Add(
                        SyntaxFactory.ParseMemberDeclaration(
                            "internal static void " + policyFunctionName + "(" + parameterType + " builder) { @" + route.Name + "(builder); }"
                        )!
                    );
                }

                var emission = new RouteEmission(
                    routeName,
                    path,
                    operation,
                    "global::Brigade.Net.Partie.Generated.BrigadeRoutes." + descriptorName,
                    "global::Brigade.Net.Partie.Generated.BrigadeRoutes." + inputName,
                    graph.Inputs,
                    routePolicies,
                    hasPolicyFunction ? ImmutableArray.Create(policyFunctionFullName) : ImmutableArray<string>.Empty,
                    graph.Request,
                    hierarchy,
                    routes[0]!.Path
                );
                adapter.Append(emitRoute(emission));
                members.Append(emitTypes?.Invoke(emission));
            }
        }

        var stubClass = declaration.WithAttributeLists(default).WithBaseList(null).WithParameterList(null).WithMembers(SyntaxFactory.List(stubs));
        foreach (var parent in declaration.Ancestors().OfType<ClassDeclarationSyntax>())
        {
            var childName = stubClass.Identifier.Text;
            var parentMembers = new List<MemberDeclarationSyntax> { stubClass };
            parentMembers.AddRange(policyWrappers.Select(wrapper => SyntaxFactory.ParseMemberDeclaration(
                "internal static void " + wrapper.Name + "(" + wrapper.ParameterType + " builder) { "
                + childName + "." + wrapper.Name + "(builder); }"
            )!));
            stubClass = parent.WithAttributeLists(default).WithBaseList(null).WithParameterList(null)
                .WithMembers(SyntaxFactory.List(parentMembers));
        }
        var stubSource = stubClass.NormalizeWhitespace().ToFullString();
        if (!group.ContainingNamespace.IsGlobalNamespace)
        {
            stubSource = "namespace " + group.ContainingNamespace.ToDisplayString() + ";\n" + stubSource;
        }

        return Finish("// <auto-generated />\n#nullable enable\n" + stubSource);
        void Report(ISymbol symbol, string message) => diagnostics.Add(Diagnostic.Create(InvalidRoute, symbol.Locations.FirstOrDefault(), message));
        GroupOutput Finish(string stubSource) => new(
            stubSource,
            new GroupSource(key, registrations.ToString(), members.ToString(), adapter.ToString(), hierarchy),
            diagnostics.ToImmutable()
        );
    }

    private static bool IsAttribute(AttributeData attribute, string name) => attribute.AttributeClass?.ContainingNamespace.ToDisplayString() == "Brigade.Net.Partie" && attribute.AttributeClass.Name == name;
    private static string GroupKey(INamedTypeSymbol group) => "Group_" + string.Concat(
        Encoding.UTF8.GetBytes(group.ToDisplayString()).Select(value => value.ToString("x2"))
    );
    private static INamedTypeSymbol? GetRegisteredType(AttributeData attribute) => attribute.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol;
    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(
        SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier)
    );
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
}
