using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Brigade.Net.Partie.Extensions.Expo.Engines.AspNetCore;

[Generator(LanguageNames.CSharp)]
public sealed class ExpoOpenApiGenerator : IIncrementalGenerator
{
    private const string ExpoAttributeName = "Brigade.Net.Expo.ExpoAttribute";
    private const string GeneratedRegexAttributeName =
        "System.Text.RegularExpressions.GeneratedRegexAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (output, compilation) => Emit(output, DiscoverModels(compilation))
        );
    }

    private static IEnumerable<INamedTypeSymbol> DiscoverModels(Compilation compilation)
    {
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (!assembly.Modules.SelectMany(module => module.ReferencedAssemblySymbols)
                .Any(reference => reference.Name == "Brigade.Net.Expo"))
            {
                continue;
            }
            foreach (var type in Types(assembly.GlobalNamespace))
            {
                if (HasExpo(type))
                {
                    yield return type;
                }
            }
        }
        foreach (var type in Types(compilation.Assembly.GlobalNamespace))
        {
            if (HasExpo(type))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> Types(INamespaceSymbol scope)
    {
        foreach (var type in scope.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in NestedTypes(type))
            {
                yield return nested;
            }
        }
        foreach (var child in scope.GetNamespaceMembers())
        {
            foreach (var type in Types(child))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> NestedTypes(INamedTypeSymbol scope)
    {
        foreach (var type in scope.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in NestedTypes(type))
            {
                yield return nested;
            }
        }
    }

    private static INamedTypeSymbol? RequestType(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;
        foreach (var syntax in method.AttributeLists.SelectMany(list => list.Attributes))
        {
            if (context.SemanticModel.GetSymbolInfo(syntax).Symbol is not IMethodSymbol constructor)
            {
                continue;
            }

            for (var type = constructor.ContainingType; type is not null; type = type.BaseType)
            {
                if (type.OriginalDefinition.ToDisplayString()
                    != "Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<THandler>")
                {
                    continue;
                }

                var handler = (INamedTypeSymbol)type.TypeArguments[0];
                var contract = handler.AllInterfaces.FirstOrDefault(item =>
                    item.OriginalDefinition.ToDisplayString() is
                        "Brigade.Net.Partie.ICommandHandler<TCommand, TResult, TContext>"
                        or "Brigade.Net.Partie.IQueryHandler<TQuery, TResult, TContext>");
                return contract?.TypeArguments[0] as INamedTypeSymbol;
            }
        }
        return null;
    }

    private static void Emit(SourceProductionContext output, IEnumerable<INamedTypeSymbol> requests)
    {
        var requestTypes = requests.GroupBy(
            type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            StringComparer.Ordinal
        ).Select(group => group.First()).ToArray();
        var models = new List<INamedTypeSymbol>();
        foreach (var request in requestTypes)
        {
            AddModels(request, models);
        }
        if (models.Count == 0)
        {
            return;
        }

        var source = new StringBuilder("""
            // <auto-generated />
            #nullable enable
            namespace Microsoft.AspNetCore.OpenApi;
            internal static class ExpoOpenApiGeneratedExtensions
            {
                public static global::Microsoft.AspNetCore.OpenApi.OpenApiOptions AddExpo(
                    this global::Microsoft.AspNetCore.OpenApi.OpenApiOptions options
                )
                {
                    options.AddSchemaTransformer(TransformSchemaAsync);
                    options.AddOperationTransformer(TransformOperationAsync);
                    return options;
                }

                private static global::System.Threading.Tasks.Task TransformSchemaAsync(
                    global::Microsoft.OpenApi.OpenApiSchema schema,
                    global::Microsoft.AspNetCore.OpenApi.OpenApiSchemaTransformerContext context,
                    global::System.Threading.CancellationToken cancellationToken
                )
                {
                    _ = cancellationToken;
            """);
        foreach (var model in models)
        {
            AppendSchemaDispatch(source, model);
        }
        source.Append("return global::System.Threading.Tasks.Task.CompletedTask;\n}\n")
            .Append("private static global::System.Threading.Tasks.Task TransformOperationAsync(")
            .Append("global::Microsoft.OpenApi.OpenApiOperation operation, ")
            .Append("global::Microsoft.AspNetCore.OpenApi.OpenApiOperationTransformerContext context, ")
            .Append("global::System.Threading.CancellationToken cancellationToken)\n{\n")
            .Append("_ = cancellationToken;\n");
        foreach (var model in models)
        {
            AppendOperationDispatch(source, model);
        }
        source.Append("return global::System.Threading.Tasks.Task.CompletedTask;\n}\n");
        AppendHelpers(source);
        source.Append("}\n");
        output.AddSource("ExpoOpenApi.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AddModels(INamedTypeSymbol type, List<INamedTypeSymbol> models)
    {
        if (HasExpo(type) && !models.Any(item => SymbolEqualityComparer.Default.Equals(item, type)))
        {
            models.Add(type);
        }
        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            var nested = Unwrap(property.Type);
            if (nested is INamedTypeSymbol named && HasExpo(named))
            {
                AddModels(named, models);
            }
        }
    }

    private static ITypeSymbol Unwrap(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
        {
            return array.ElementType;
        }
        if (type is INamedTypeSymbol named)
        {
            if (named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                return named.TypeArguments[0];
            }
            var enumerable = named.AllInterfaces.Concat([named]).FirstOrDefault(item =>
                item.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
            if (enumerable is not null && named.SpecialType != SpecialType.System_String)
            {
                return enumerable.TypeArguments[0];
            }
        }
        return type;
    }

    private static bool HasExpo(INamedTypeSymbol type) => type.GetAttributes().Any(attribute =>
        attribute.AttributeClass?.ToDisplayString() == ExpoAttributeName);

    private static void AppendSchemaDispatch(StringBuilder source, INamedTypeSymbol model)
    {
        source.Append("if (context.JsonTypeInfo.Type == typeof(")
            .Append(model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append("))\n{\n")
            .Append("foreach (var jsonProperty in context.JsonTypeInfo.Properties)\n{\n")
            .Append("if (jsonProperty.AttributeProvider is not global::System.Reflection.PropertyInfo propertyInfo ")
            .Append("|| schema.Properties is null || !schema.Properties.TryGetValue(jsonProperty.Name, out var rawSchema) ")
            .Append("|| rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)\n{\ncontinue;\n}\n")
            .Append("switch (propertyInfo.Name)\n{\n");
        foreach (var property in model.GetMembers().OfType<IPropertySymbol>()
            .Where(property => !property.IsStatic && !property.IsIndexer))
        {
            var rules = Rules(property, model).ToArray();
            if (rules.Length == 0)
            {
                continue;
            }
            source.Append("case ").Append(Literal(property.Name)).Append(":\n");
            foreach (var rule in rules)
            {
                AppendRule(source, rule, AppliesToItems(property, rule));
            }
            source.Append("break;\n");
        }
        source.Append("}\n}\nreturn global::System.Threading.Tasks.Task.CompletedTask;\n}\n");
    }

    private static void AppendOperationDispatch(StringBuilder source, INamedTypeSymbol model)
    {
        var bound = model.GetMembers().OfType<IPropertySymbol>().Select(property => new
        {
            Property = property,
            Binding = property.GetAttributes().FirstOrDefault(attribute =>
                attribute.AttributeClass?.ContainingNamespace.ToDisplayString() == "Brigade.Net.Partie"
                && attribute.AttributeClass.Name is "FromPathAttribute" or "FromParamsAttribute"
                    or "FromMetadataAttribute" or "FromPayloadAttribute")
        }).Where(item => item.Binding is not null).ToArray();
        if (bound.Length == 0)
        {
            return;
        }

        var dtoType = model.ContainingNamespace.IsGlobalNamespace ? string.Empty
            : model.ContainingNamespace.ToDisplayString() + ".";
        dtoType += model.Name + "Dto";
        foreach (var item in bound)
        {
            var rules = Rules(item.Property, model).ToArray();
            if (rules.Length == 0)
            {
                continue;
            }
            source.Append("foreach (var binding in context.Description.ParameterDescriptions)\n{\n")
                .Append("if (binding.ModelMetadata?.ContainerType != typeof(global::").Append(dtoType)
                .Append(") || binding.ModelMetadata.PropertyName != ").Append(Literal(item.Property.Name))
                .Append(")\n{\ncontinue;\n}\n");
            if (item.Binding!.AttributeClass?.Name == "FromPayloadAttribute")
            {
                var format = item.Binding.NamedArguments.FirstOrDefault(pair => pair.Key == "Format")
                    .Value.Value as int? ?? 0;
                if (format == 0)
                {
                    if (rules.Any(rule => rule.Kind == "Required"))
                    {
                        source.Append("if (operation.RequestBody is global::Microsoft.OpenApi.OpenApiRequestBody requestBody)\n")
                            .Append("{\nrequestBody.Required = true;\n}\n");
                    }
                    source.Append("}\n");
                    continue;
                }

                source.Append("var bodySchema = operation.RequestBody?.Content?.Values.FirstOrDefault()?.Schema ")
                    .Append("as global::Microsoft.OpenApi.OpenApiSchema;\n")
                    .Append("if (bodySchema?.Properties is null || !bodySchema.Properties.TryGetValue(binding.Name, out var rawSchema) ")
                    .Append("|| rawSchema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)\n")
                    .Append("{\ncontinue;\n}\n");
                foreach (var rule in rules)
                {
                    AppendOperationRule(source, rule, AppliesToItems(item.Property, rule));
                }
                source.Append("}\n");
                continue;
            }
            source.Append("var parameter = operation.Parameters?.FirstOrDefault(candidate => candidate.Name == binding.Name);\n")
                .Append("if (parameter?.Schema is not global::Microsoft.OpenApi.OpenApiSchema propertySchema)\n")
                .Append("{\ncontinue;\n}\n");
            foreach (var rule in rules)
            {
                AppendOperationRule(source, rule, AppliesToItems(item.Property, rule));
            }
            source.Append("}\n");
        }
    }

    private static IEnumerable<Rule> Rules(IPropertySymbol property, INamedTypeSymbol model)
    {
        foreach (var attribute in property.GetAttributes())
        {
            var name = attribute.AttributeClass?.Name;
            var fullName = attribute.AttributeClass?.ToDisplayString();
            var message = Message(attribute);
            if (name == "IsRequiredAttribute")
            {
                yield return new("Required", null, null, message);
            }
            else if (name is not null
                && name.StartsWith("StringMatches", StringComparison.Ordinal)
                && attribute.AttributeClass?.GetMembers("Pattern").OfType<IFieldSymbol>()
                    .Any(field => field.HasConstantValue) == true)
            {
                var patternField = attribute.AttributeClass?.GetMembers("Pattern")
                    .OfType<IFieldSymbol>().FirstOrDefault();
                if (patternField?.ConstantValue is string pattern)
                {
                    yield return new("Pattern", pattern, null, message);
                }
            }
            else if (name is "StringHasMinimumLengthAttribute" or "ItemsHasMinimumLengthAttribute")
            {
                yield return new(name.StartsWith("String", StringComparison.Ordinal)
                    ? "StringMinimumLength" : "ItemsMinimumLength", Value(attribute), null, message);
            }
            else if (name is "StringHasMaximumLengthAttribute" or "ItemsHasMaximumLengthAttribute")
            {
                yield return new(name.StartsWith("String", StringComparison.Ordinal)
                    ? "StringMaximumLength" : "ItemsMaximumLength", Value(attribute), null, message);
            }
            else if (name is "StringHasExactLengthAttribute" or "ItemsHasExactLengthAttribute")
            {
                yield return new(name.StartsWith("String", StringComparison.Ordinal)
                    ? "StringExactLength" : "ItemsExactLength", Value(attribute), null, message);
            }
            else if (name is "StringIsNotEmptyAttribute" or "ItemsIsNotEmptyAttribute")
            {
                yield return new(name.StartsWith("String", StringComparison.Ordinal)
                    ? "StringNotEmpty" : "ItemsNotEmpty", null, null, message);
            }
            else if (name is "StringIsNotWhiteSpaceAttribute" or "EnumIsDefinedAttribute")
            {
                yield return new("Inexact", null, name, message);
            }
            else if (TryComparison(attribute, out var comparison))
            {
                yield return comparison;
            }
            else if (Prefab(name) is { } prefab)
            {
                yield return prefab;
            }
            else if (fullName == "Brigade.Net.Expo.CustomValidationAttribute"
                || attribute.AttributeClass?.AllInterfaces.Any(item =>
                    item.ToDisplayString() == "Brigade.Net.Expo.IExpoValidationAttribute") == true)
            {
                yield return new("Inexact", null, name, message);
            }
        }

        foreach (var syntaxReference in property.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is not PropertyDeclarationSyntax declaration)
            {
                continue;
            }
            foreach (var attribute in declaration.AttributeLists.SelectMany(list => list.Attributes))
            {
                var name = attribute.Name.ToString().Split('.').Last();
                if (name.StartsWith("StringMatches", StringComparison.Ordinal))
                {
                    name = name.Substring("StringMatches".Length)
                        .Replace("Attribute", string.Empty);
                    var member = model.GetMembers(name).FirstOrDefault();
                    var generated = member?.GetAttributes().FirstOrDefault(item =>
                        item.AttributeClass?.ToDisplayString() == GeneratedRegexAttributeName);
                    if (generated?.ConstructorArguments.FirstOrDefault().Value is string pattern)
                    {
                        yield return new("Pattern", pattern, null, null);
                    }
                }
            }
        }
    }

    private static bool TryComparison(AttributeData attribute, out Rule rule)
    {
        var comparisonType = attribute.AttributeClass;
        while (comparisonType is not null && comparisonType.ContainingNamespace.ToDisplayString()
            != "Brigade.Net.Expo")
        {
            comparisonType = comparisonType.BaseType;
        }
        var name = comparisonType?.Name ?? string.Empty;
        var propertyComparison = name.EndsWith("XAttribute", StringComparison.Ordinal);
        var kind = name.StartsWith("IsGreaterThanOrEqual", StringComparison.Ordinal) ? "Minimum"
            : name.StartsWith("IsGreaterThan", StringComparison.Ordinal) ? "ExclusiveMinimum"
            : name.StartsWith("IsLessThanOrEqual", StringComparison.Ordinal) ? "Maximum"
            : name.StartsWith("IsLessThan", StringComparison.Ordinal) ? "ExclusiveMaximum"
            : name.StartsWith("IsNotEqual", StringComparison.Ordinal) ? "NotEqual"
            : name.StartsWith("IsEqual", StringComparison.Ordinal) ? "Equal" : string.Empty;
        if (kind.Length == 0)
        {
            rule = null!;
            return false;
        }
        rule = propertyComparison
            ? new("Inexact", null, kind, Message(attribute))
            : new(kind, Value(attribute), null, Message(attribute));
        return true;
    }

    private static Rule? Prefab(string? name)
    {
        return name switch
        {
            "StringMatchesEmailAttribute" => new("FormatPattern", "email", @"^[^@\s]+@[^@\s]+\.[^@\s]+$", null),
            "StringMatchesUrlAttribute" => new("Format", "uri", null, null),
            "StringMatchesUuidAttribute" => new("Format", "uuid", null, null),
            "StringMatchesIpAddressAttribute" => new("Format", "ip", null, null),
            "StringMatchesIpv4AddressAttribute" => new("Format", "ipv4", null, null),
            "StringMatchesIpv6AddressAttribute" => new("Format", "ipv6", null, null),
            "StringMatchesBase64Attribute" => new("Format", "byte", null, null),
            "StringMatchesPhoneNumberAttribute" => new("Pattern", @"^\+[1-9]\d{1,14}$", null, null),
            "StringMatchesHexColorAttribute" => new("Pattern", @"^#?(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$", null, null),
            "StringMatchesSlugAttribute" => new("Pattern", @"^[a-z0-9]+(?:-[a-z0-9]+)*$", null, null),
            "StringMatchesAlphaAttribute" => new("Pattern", @"^\p{L}+$", null, null),
            "StringMatchesAlphaNumericAttribute" => new("Pattern", @"^[\p{L}\p{Nd}]+$", null, null),
            "StringMatchesDigitsAttribute" => new("Pattern", @"^\d+$", null, null),
            _ => null
        };
    }

    private static bool AppliesToItems(IPropertySymbol property, Rule rule)
    {
        return GetEnumerableElementType(property.Type) is not null
            && rule.Kind is not "Required" and not "ItemsMinimumLength"
                and not "ItemsMaximumLength" and not "ItemsExactLength" and not "ItemsNotEmpty";
    }

    private static ITypeSymbol? GetEnumerableElementType(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            return null;
        }
        if (type is IArrayTypeSymbol array)
        {
            return array.ElementType;
        }
        return type.AllInterfaces.Concat([type]).OfType<INamedTypeSymbol>()
            .FirstOrDefault(item => item.OriginalDefinition.SpecialType
                == SpecialType.System_Collections_Generic_IEnumerable_T)?.TypeArguments[0];
    }

    private static void AppendRule(StringBuilder source, Rule rule, bool appliesToItems)
    {
        var schema = appliesToItems
            ? "((global::Microsoft.OpenApi.OpenApiSchema)propertySchema.Items!)"
            : "propertySchema";
        switch (rule.Kind)
        {
            case "Required": source.Append("schema.Required ??= new global::System.Collections.Generic.HashSet<string>(); schema.Required.Add(jsonProperty.Name);\n"); break;
            case "Minimum": source.Append(schema).Append(".Minimum = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "ExclusiveMinimum": source.Append(schema).Append(".ExclusiveMinimum = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "Maximum": source.Append(schema).Append(".Maximum = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "ExclusiveMaximum": source.Append(schema).Append(".ExclusiveMaximum = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "Equal": source.Append(schema).Append(".Const = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "NotEqual": source.Append(schema).Append(".Not = new global::Microsoft.OpenApi.OpenApiSchema { Const = ").Append(Literal(rule.Value!)).Append(" };\n"); break;
            case "StringMinimumLength": source.Append(schema).Append(".MinLength = ").Append(rule.Value).Append(";\n"); break;
            case "StringMaximumLength": source.Append(schema).Append(".MaxLength = ").Append(rule.Value).Append(";\n"); break;
            case "StringExactLength": source.Append(schema).Append(".MinLength = ").Append(rule.Value).Append("; ").Append(schema).Append(".MaxLength = ").Append(rule.Value).Append(";\n"); break;
            case "ItemsMinimumLength": source.Append(schema).Append(".MinItems = ").Append(rule.Value).Append(";\n"); break;
            case "ItemsMaximumLength": source.Append(schema).Append(".MaxItems = ").Append(rule.Value).Append(";\n"); break;
            case "ItemsExactLength": source.Append(schema).Append(".MinItems = ").Append(rule.Value).Append("; ").Append(schema).Append(".MaxItems = ").Append(rule.Value).Append(";\n"); break;
            case "StringNotEmpty": source.Append(schema).Append(".MinLength = 1;\n"); break;
            case "ItemsNotEmpty": source.Append(schema).Append(".MinItems = 1;\n"); break;
            case "Pattern": source.Append(schema).Append(".Pattern = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "Format": source.Append(schema).Append(".Format = ").Append(Literal(rule.Value!)).Append(";\n"); break;
            case "FormatPattern": source.Append(schema).Append(".Format = ").Append(Literal(rule.Value!)).Append("; ").Append(schema).Append(".Pattern = ").Append(Literal(rule.Extra!)).Append(";\n"); break;
            default: source.Append("AddInexact(").Append(schema).Append(", ").Append(Literal(rule.Extra ?? "Custom")).Append(");\n"); break;
        }
    }

    private static void AppendOperationRule(StringBuilder source, Rule rule, bool appliesToItems)
    {
        if (rule.Kind == "Required")
        {
            source.Append("parameter.Required = true;\n");
            return;
        }

        var temporary = new StringBuilder();
        AppendRule(temporary, rule, appliesToItems);
        source.Append(temporary.ToString().Replace("schema.Required", "propertySchema.Required")
            .Replace("jsonProperty.Name", "binding.Name"));
    }

    private static string? Value(AttributeData attribute)
    {
        var value = attribute.ConstructorArguments.FirstOrDefault().Value;
        return value is null ? null : Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string? Message(AttributeData attribute) => attribute.ConstructorArguments
        .LastOrDefault(item => item.Type?.SpecialType == SpecialType.System_String).Value as string;

    private static void AppendHelpers(StringBuilder source)
    {
        source.Append("""
            private static void ApplyMinimum(global::Microsoft.OpenApi.OpenApiSchema schema, int length)
            {
                if ((schema.Type & global::Microsoft.OpenApi.JsonSchemaType.Array) != 0)
                {
                    schema.MinItems = length;
                    return;
                }
                schema.MinLength = length;
            }
            private static void ApplyMaximum(global::Microsoft.OpenApi.OpenApiSchema schema, int length)
            {
                if ((schema.Type & global::Microsoft.OpenApi.JsonSchemaType.Array) != 0)
                {
                    schema.MaxItems = length;
                    return;
                }
                schema.MaxLength = length;
            }
            private static void AddInexact(global::Microsoft.OpenApi.IOpenApiSchema schema, string rule)
            {
                var text = "Expo validation rule: " + rule + ".";
                schema.Description = global::System.String.IsNullOrWhiteSpace(schema.Description)
                    ? text : schema.Description + " " + text;
            }
            """);
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private sealed class Rule(string kind, string? value, string? extra, string? message)
    {
        public string Kind { get; } = kind;
        public string? Value { get; } = value;
        public string? Extra { get; } = extra;
        public string? Message { get; } = message;
    }
}
