<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Brigade.Net.Example.Domain.csproj" />
    <ProjectReference Include="..\..\Partie\AspNetCore\Brigade.Net.Partie.AspNetCore.csproj" />
    <ProjectReference Include="..\ServiceDefaults\Brigade.Net.Example.ServiceDefaults.csproj" />

    <ProjectReference Include="..\..\Partie\Engines\AspNetCore\Brigade.Net.Partie.Engines.AspNetCore.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"/>
  </ItemGroup>

</Project>
