// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Expo;
[global::Brigade.Net.Partie.BundleRegistration(typeof(global::Brigade.Net.Partie.Extensions.Expo.ExpoSystemBundle<, >))]
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @ExpoSystemBundleAttribute() : global::System.Attribute
{
}
