// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Expo;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Partie.Extensions.Expo.ExpoValidationPartie<, >), false)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class @ExpoValidationPartieAttribute() : global::System.Attribute
{
}
