// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Expo;
[global::Brigade.Net.Partie.Engines.AspNetCore.RoutePolicy(typeof(global::Brigade.Net.Partie.Extensions.Expo.ExpoValidationRoutePolicy<>))]
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @ExpoValidationRoutePolicyAttribute : global::System.Attribute
{
}
