// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.Extensions.Mise;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Partie.Extensions.Mise.DbReaderProvider<, >), true)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class @DbReaderProviderAttribute() : global::System.Attribute
{
}
