// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.AspNetCore;
[global::Brigade.Net.Partie.Registration(typeof(global::Brigade.Net.Partie.AspNetCore.HttpResultPartie<, >), false)]
[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class @HttpResultPartieAttribute() : global::System.Attribute
{
}
