// <auto-generated />
#nullable enable
namespace Brigade.Net.Partie.AspNetCore;
[global::Brigade.Net.Partie.BundleRegistration(typeof(global::Brigade.Net.Partie.AspNetCore.PartieSystemBundle<, >))]
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @PartieSystemBundleAttribute() : global::System.Attribute
{
}
