// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.ValidateV1;
[global::Brigade.Net.Expo.ExpoAttribute()]
public sealed class OrderValidateV1CmdDto
{
    [global::Brigade.Net.Expo.IsRequiredAttribute("The validation payload is required.")]
    [global::Microsoft.AspNetCore.Mvc.FromBody]
    public global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidationPayload? @Body { get; set; } = default!;

    [global::Brigade.Net.Expo.StringIsNotEmptyAttribute(null)]
    [global::Microsoft.AspNetCore.Mvc.FromHeader(Name = "X-Validation-Code")]
    public string? @ValidationCode { get; set; } = default!;
}
