// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Orders.ValidateV1;
internal static class @OrderValidateV1HandlerRoute
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PostAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "POST")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PutAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "PUT")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PatchAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "PATCH")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class DeleteAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "DELETE")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class HeadAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "HEAD")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class OptionsAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "OPTIONS")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class TraceAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "TRACE")
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class ConnectAttribute(string path = "") : global::Brigade.Net.Partie.Engines.AspNetCore.HandlerRouteAttribute<global::Brigade.Net.Example.Domain.Orders.ValidateV1.OrderValidateV1Handler>(path, "CONNECT")
    {
    }
}
