using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Brigade.Net.Partie.Generator;

/// <summary>Generates registration attributes for records whose constructor lists route steps.</summary>
public static class BundleDeclarations
{
    public static IncrementalValuesProvider<GeneratedDeclaration> Create(
        IncrementalGeneratorInitializationContext context
    )
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is RecordDeclarationSyntax,
            static (syntax, token) => (
                Type: (INamedTypeSymbol)syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, token)!,
                Compilation: syntax.SemanticModel.Compilation
            )
        ).Where(item => BundleMembers.IsBundle(item.Type, item.Compilation));
        context.RegisterSourceOutput(candidates, (output, item) =>
        {
            BundleMembers.Parameters(item.Type, item.Compilation, message => output.ReportDiagnostic(
                Diagnostic.Create(BrigadeGeneratorCore.InvalidRoute, item.Type.Locations.FirstOrDefault(), message)));
        });

        return candidates.Select((item, _) => Describe(item.Type, item.Compilation)!.Value)
            .Collect().SelectMany((items, _) => items.Distinct());
    }

    /// <summary>Describes a bundle declared locally or in a referenced assembly.</summary>
    public static GeneratedDeclaration? Describe(INamedTypeSymbol type, Compilation compilation)
    {
        if (!BundleMembers.IsBundle(type, compilation))
        {
            return null;
        }

        var parameters = BundleMembers.Parameters(type, compilation, _ => { });
        var registeredType = type.IsGenericType ? type.ConstructUnboundGenericType() : type;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        if (ns.Length != 0)
        {
            source.Append("namespace ").Append(ns).Append(";\n");
        }
        source.Append("[global::Brigade.Net.Partie.BundleRegistration(typeof(")
            .Append(SymbolEmission.TypeName(registeredType)).Append("))]\n")
            .Append("[global::System.AttributeUsage(global::System.AttributeTargets.Class | ")
            .Append("global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]\n")
            .Append("internal sealed class @").Append(type.Name).Append("Attribute(")
            .Append(string.Join(", ", parameters.Select(ContextParameters.Declaration)))
            .Append(") : global::System.Attribute\n{\n");
        foreach (var parameter in parameters)
        {
            source.Append("public ").Append(SymbolEmission.TypeName(parameter.Type)).Append(" @")
                .Append(parameter.Name).Append(" { get; } = @").Append(parameter.Name).Append(";\n");
        }
        source.Append("}\n");
        return new GeneratedDeclaration((ns.Length == 0 ? "" : ns + "/") + type.Name + "Attribute.g.cs", source.ToString());
    }
}
