using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Brigade.Net.Partie.Generator;

/// <summary>Describes a generated, transport-neutral Partie or Provider registration attribute.</summary>
public static class RegistrationDeclarations
{
    public static GeneratedDeclaration? Describe(INamedTypeSymbol type, Compilation compilation)
    {
        var contract = type.AllInterfaces.FirstOrDefault(candidate =>
            StepContracts.IsStep(candidate, compilation)
        );
        if (contract is null)
        {
            return null;
        }
        var provider = StepContracts.IsProvider(contract, compilation);
        var parameters = ContextParameters.Read(contract.TypeArguments[1], compilation);
        var registeredType = type.IsGenericType ? type.ConstructUnboundGenericType() : type;
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(";\n");
        }
        source.Append("[global::Brigade.Net.Partie.Registration(typeof(")
            .Append(SymbolEmission.TypeName(registeredType))
            .Append("), ")
            .Append(provider ? "true" : "false")
            .Append(")]\n")
            .Append("[global::System.AttributeUsage(global::System.AttributeTargets.Method")
            .Append(" | global::System.AttributeTargets.Class")
            .Append(", AllowMultiple = true, Inherited = false)]\ninternal sealed class @")
            .Append(type.Name)
            .Append("Attribute(")
            .Append(string.Join(", ", parameters.Select(ContextParameters.Declaration)))
            .Append(") : global::System.Attribute\n{\n");
        foreach (var parameter in parameters)
        {
            source.Append("public ").Append(SymbolEmission.TypeName(parameter.Type)).Append(" @")
                .Append(parameter.Name).Append(" { get; } = @").Append(parameter.Name).Append(";\n");
        }
        source.Append("}\n");
        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? ""
            : type.ContainingNamespace.ToDisplayString() + "/";
        return new GeneratedDeclaration(ns + type.Name + "Attribute.g.cs", source.ToString());
    }
}
