// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Web.RoutePolicies;
[global::Brigade.Net.Partie.Engines.AspNetCore.RoutePolicy(typeof(global::Brigade.Net.Example.Web.RoutePolicies.FakeHeaderCheckRoutePolicy<>))]
[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
internal sealed class @FakeHeaderCheckRoutePolicyAttribute : global::System.Attribute
{
}
