// <auto-generated />
#nullable enable
namespace Brigade.Net.Example.Domain.Accounts.UpdatePostgreSqlV1;
public sealed class AccountUpdatePostgreSqlV1CmdDto
{
    [global::Microsoft.AspNetCore.Mvc.FromQuery]
    public int @Id { get; set; } = default!;

    [global::Microsoft.AspNetCore.Mvc.FromQuery]
    public string? @Note { get; set; } = default!;
}
